name: Vercel deployment

on: [push, pull_request]

jobs:
  transform-api:
    name: Transform API

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Run transformation script
        run: yarn run transform
      - name: Upload transformed
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api

  deploy:
    name: Deploy to Vercel

    runs-on: ubuntu-latest

    needs: transform-api

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
